# Generated by Django 6.0.2 on 2026-03-02 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=30, verbose_name='Restante do nome')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail')),
                ('phone_number', models.CharField(max_length=11, verbose_name='WhatsApp')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Bairro')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='Nome de usuário')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='Cliente Ativo')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Delivery_Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20, verbose_name='Nome Completo')),
                ('identity_number', models.CharField(max_length=20, unique=True, verbose_name='Identificação (CPF)')),
                ('plate_number', models.CharField(help_text='Formato: ABC-1234', max_length=8, unique=True, verbose_name='Placa do Veículo')),
                ('phone_number', models.CharField(max_length=11, verbose_name='WhatsApp')),
                ('active', models.BooleanField(default=True, verbose_name='Entregador Ativo')),
            ],
            options={
                'verbose_name': 'Entregador',
                'verbose_name_plural': 'Entregadores',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Primeiro Nome')),
                ('last_name', models.CharField(max_length=30, verbose_name='Restante do nome')),
                ('phone_number', models.CharField(max_length=11, verbose_name='WhatsApp')),
                ('address', models.CharField(max_length=100, verbose_name='Endereço')),
                ('neighborhood', models.CharField(max_length=50, verbose_name='Bairro')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True, verbose_name='Funcionário Ativo')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
            },
        ),
        migrations.CreateModel(
            name='Financial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Data da Transação')),
                ('description', models.CharField(max_length=100, verbose_name='Descrição da Transação')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Transação')),
                ('transaction_type', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Tipo de Transação')),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Número da Nota Fiscal')),
            ],
            options={
                'verbose_name': 'Financeiro',
                'verbose_name_plural': 'Financeiros',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, unique=True, verbose_name='Nome do Grupo')),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, unique=True, verbose_name='Nome do Produto')),
                ('type', models.CharField(choices=[('A', 'Acompanhamento'), ('B', 'Bebida'), ('L', 'Lanche'), ('S', 'Sobremesa'), ('R', 'Refeição'), ('P', 'Porção')], max_length=1, verbose_name='Tipo do Produto')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição do Produto')),
                ('kind', models.CharField(choices=[('Q', 'Quente'), ('F', 'Frio'), ('G', 'Gelado')], max_length=1, verbose_name='Forma de servir')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Produto')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Foto do Produto')),
                ('yeld_servings', models.PositiveIntegerField(verbose_name='Rendimento do Produto')),
            ],
            options={
                'verbose_name': 'Cardápio',
                'verbose_name_plural': 'Cardápios',
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nome do Insumo')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Compra')),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Venda')),
                ('stock_quantity', models.PositiveIntegerField(verbose_name='Quantidade em Estoque')),
                ('minimum_stock', models.PositiveIntegerField(verbose_name='Estoque Mínimo')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.group', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Insumo',
                'verbose_name_plural': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade em Estoque')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.input', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Estoque',
                'verbose_name_plural': 'Estoques',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=10, unique=True, verbose_name='Número do Pedido')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('quantity', models.PositiveIntegerField(verbose_name='Quantidade')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Total')),
                ('payment_method', models.CharField(choices=[('CC', 'Cartão de Crédito'), ('CD', 'Cartão de Débito'), ('C', 'Dinheiro'), ('P', 'Pix')], max_length=2, verbose_name='Forma de Pagamento')),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Pago')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer', verbose_name='Cliente')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.menu', verbose_name='Item do Cardápio')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_start', models.DateTimeField(auto_now_add=True, verbose_name='Início da Entrega')),
                ('delivery_end', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Entrega')),
                ('delivery_status', models.CharField(choices=[('P', 'Pendente'), ('A', 'Andamento'), ('C', 'Concluída'), ('X', 'Cancelada')], max_length=1, verbose_name='Status da Entrega')),
                ('delivery_driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.delivery_driver', verbose_name='Entregador')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Deliveries',
            },
        ),
    ]
