# Generated by Django 6.0.2 on 2026-03-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='username',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(default='null', max_length=20, unique=True, verbose_name='Código de Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='delivery',
            name='delivery_status',
            field=models.CharField(choices=[('P', 'Pendente'), ('A', 'Andamento'), ('C', 'Concluída'), ('X', 'Cancelada')], default='P', max_length=1, verbose_name='Status da Entrega'),
        ),
    ]
